site_name: Usługi Informatyczne Szymon Brzostek
site_url: https://www.uisb.net
theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode